#!/bin/bash

PROJECT_PATH="D:/Magento/ce/v2.3.0"

MYSQL_HOST="localhost"
MYSQL_USERNAME="root"
MYSQL_PASSWORD="root"
MYSQL_DATABASE="magento-ce-2-3-0"

MAGENTO_BASE_URL="http://magento-ce-2-3-0.local"
MAGENTO_BACKEND_FRONTNAME="admin"
MAGENTO_ADMIN_USER="admin"
MAGENTO_ADMIN_PASSWORD="admin123"
MAGENTO_ADMIN_FIRSTNAME="admin"
MAGENTO_ADMIN_LASTNAME="admin"
MAGENTO_ADMIN_EMAIL="noreply@domain.com"
MAGENTO_LANGUAGE=en_US
MAGENTO_CURRENCY=USD
MAGENTO_TIMEZONE=America/Los_Angeles
MAGENTO_PUBLIC_KEY=6dcd44888ee045d44dd40f0971aaa3ab
MAGENTO_PRIVATE_KEY=7c260c09f71864b744003bb4a08d6ae7
